using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace BiometricsSystem
{
    public partial class FaceRecognition : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }



        public void CapturePhoto()
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = @"Path-To-Python\python.exe"; // Specify the path of python interpreter if necessary
            start.Arguments = string.Format("{0} {1}", @"Path-To-Python-Script\show.py", "");
            start.UseShellExecute = false; // Do not use OS shell
            start.RedirectStandardOutput = true; // Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    Debug.WriteLine(result);
                }
            }
        }

        protected void btnCapturePhoto_Click(object sender, EventArgs e)
        {
            CapturePhoto();
        }
    }
}